# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a6f90fa20eb572bf6eab3be268f15fb07344593422f5c08e95da8771defd83fa94e8282ae2e33fa7909118a49f2bf286eb97c1eaa8ae725c32f6f86359da99d

test:
  secret_key_base: 64e9b29f5ec9a3fb7274d464b1c22eef53209a0ef00070d495553ad9a9a5c6f5d8aea99edc65296ac0b556c8482fbf36f007221a6e1f71b6ba9e3e8dc2cc7633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
